### ISSUE TITLE
what's meaning of row chip?

### ISSUE THREAD

**Issue by 0x7a657573** [IoTReady/a9_gsm_gps_library#18]
In the [GPRS_C_SDK](https://github.com/Ai-Thinker-Open/GPRS_C_SDK) repository, I see say you can use this SDK with row chip!
```This SDK can be also applied to RDA8955 raw chip 也可直接在RDA8955芯片上运行```
you know what's meaning of row chip?

**Comment by KaranRajPradhan** [comment]
@0x7a657573 This repository is a helper library to allow easy usage of the GPRS_C_SDK you mentioned above. We DO NOT own the GPRS_C_SDK repository.

That said, I think what AiThinker mean by "This SDK can be also applied to RDA8955 raw chip" is that you can use their SDK to directly program the RDA8955 chip. The A9 and A9G are modules based on RDA8955 chip. So, when you are programming the AiThinker modules, you are actually programming the RDA8955 "raw" chip inside it.
