### ISSUE TITLE
Integrate clang-format and clang-tidy

### ISSUE THREAD

**Issue by tejpochiraju** [IoTReady/a9_gsm_gps_library#6]

**Comment by hairyhoncho** [comment]
Simplest way to integrate is to use the plugins from VSC Marketplace.
[clang-format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format)

keyboard shortcut (usually Ctrl+⇧+F on Windows, Ctrl+⇧+I on Linux, and ⇧+⌥+F on macOS).

To automatically format a file on save, add the following to your vscode settings.json file:

```
{
    "editor.formatOnSave": true
}
```

[clang-tidy](https://marketplace.visualstudio.com/items?itemName=notskm.clang-tidy)
[documentation](https://clang.llvm.org/extra/clang-tidy/)
