### ISSUE TITLE
Some code blocks not parsed correctly

### ISSUE THREAD

**Issue by tejpochiraju** [IoTReady/a9_gsm_gps_library#9]
E.g. on https://iotready.co/a9_gsm_gps_library/index.html#autotoc_md33

![image](https://user-images.githubusercontent.com/9004891/109912892-f4626e80-7cd2-11eb-8310-446df9ef3a87.png)

**Comment by hairyhoncho** [comment]
Incorrect markdown syntax in source README.md file. Leading space before block quote caused it not be be parsed as a markdown directive
